application: zettasecond
version: 1
runtime: python
api_version: 1

handlers:

- url: /css/style.css
  static_files: template/css/style.css
  upload: template/css/style.css
  
- url: /images
  static_dir: template/images


- url: /.*
  script: zeta.py
  secure: always